[package]
name = "godot_data"
version = "0.1.0"
edition = "2021"

[features]
serjson = []
serjsonpretty = []
dejson = []
serbin = []
debin = []
minname = []

[dependencies]
nanoserde = {version = "0.1.37"}
godot_macros = {path = "../godot_macros"}